///////////////////////////////////////////////////////////
//  NewModel.as
//  Macromedia ActionScript Implementation of the Class NewModel
//  Generated by Enterprise Architect
//  Created on:      06-Nov-2007 13:48:24
//  Original author: USER
///////////////////////////////////////////////////////////

/////////////////////////////////////////////////////////////////////////
// Copyright (c) 2007-09 LTRI, London Metropolitan Uni. All rights reserved.
// An Open Source Release under the GPL v3 licence  (see http://www.gnu.org/licenses/).
// Authors: Tom Boyle, Nils Millahn, Musbah Sagar, Martin Agombar.
// See http://www.glomaker.org for full details
/////////////////////////////////////////////////////////////////////////

package org.glomaker.patternmaker.model
{
	import org.glomaker.patternmaker.view.BaseModel;
	import org.glomaker.patternmaker.view.INewModel;

	/**
	 * @author USER
	 * @version 1.0
	 * @created 06-Nov-2007 13:48:24
	 */
	public class NewModel extends BaseModel implements INewModel {
		/**
		     * 
		     * @param value    value
		     */
		public function setSomething(value:String):void {
		}

		public function getSomething():String {
		}

		/**
		     * 
		     * @param value    value
		     */
		public function setMenu(value:String):void {
		}

		public function getMenuList():Array {
		}

	}//end NewModel

}