///////////////////////////////////////////////////////////
//  BaseController.as
//  Macromedia ActionScript Implementation of the Class BaseController
//  Generated by Enterprise Architect
//  Created on:      06-Nov-2007 13:48:23
//  Original author: USER
///////////////////////////////////////////////////////////

/////////////////////////////////////////////////////////////////////////
// Copyright (c) 2007-09 LTRI, London Metropolitan Uni. All rights reserved.
// An Open Source Release under the GPL v3 licence  (see http://www.gnu.org/licenses/).
// Authors: Tom Boyle, Nils Millahn, Musbah Sagar, Martin Agombar.
// See http://www.glomaker.org for full details
/////////////////////////////////////////////////////////////////////////

package org.glomaker.patternmaker.controller
{
	import org.glomaker.patternmaker.data.GlobalPoint;
	
	import flash.events.*;
	import flash.geom.Point;
	
	/**
	 * @author USER
	 * @version 1.0
	 * @created 06-Nov-2007 13:48:23
	 */
	public class BaseController implements IController
	{
	    protected var model: Object;

	    /**
	     * CONSTRUCTOR
	     * 
	     * @param aModel    aModel
	     */
	    public function BaseController(aModel:Object)
	    {
			model = aModel;
	    }

		public function menuBtnHandler(e:MouseEvent, loc:GlobalPoint): void
	    {
	    	// intentionally empty - override in subclass
	    }
		

	}//end BaseController

}