///////////////////////////////////////////////////////////
//  BaseModel.as
//  Macromedia ActionScript Implementation of the Class BaseModel
//  Generated by Enterprise Architect
//  Created on:      06-Nov-2007 13:48:23
//  Original author: USER
///////////////////////////////////////////////////////////

/////////////////////////////////////////////////////////////////////////
// Copyright (c) 2007-09 LTRI, London Metropolitan Uni. All rights reserved.
// An Open Source Release under the GPL v3 licence  (see http://www.gnu.org/licenses/).
// Authors: Tom Boyle, Nils Millahn, Musbah Sagar, Martin Agombar.
// See http://www.glomaker.org for full details
/////////////////////////////////////////////////////////////////////////

package org.glomaker.patternmaker.model
{
	import org.glomaker.patternmaker.events.*;
	
	import flash.display.Stage;
	import flash.errors.*;
	import flash.events.*;
	
	import org.glomaker.patternmaker.events.ModelEvent;

	/**
	 * @author USER
	 * @version 1.0
	 * @created 06-Nov-2007 13:48:23
	 */

	public class BaseModel extends EventDispatcher implements IBaseModel {
		/**
		     * CONSTRUCTOR
		     */
		protected var patternXML:XML;
		protected var GLO_manifest:XML;
		protected var nodeArray:Array;
		protected var path:String;
		protected var menuList:Array;
		private var menuID:String;
		private var selItem:Object;
		protected var theStage:Stage;
		protected var importType:String;

		public function BaseModel(aStage:Stage) {
			patternXML = null;
			nodeArray = new Array();
			menuList = new Array();
			menuID = "EASA";//Default pattern.
			//setXML("xml/default.xml");
			//setXML("xml/temp.xml");
			//importType = "default";
			selItem = new Object();
			selItem.label = "";
			selItem.data = "";
			selItem.index = 0;
			theStage = aStage;
		}
		private function onError(e:IOErrorEvent):void {
			var err:Error = new Error("XML failed to load");
			throw err;
			
		}
		
		public function setImportType(type:String):void{
			importType = type;
			update("setImportType");
		}
		
		public function getImportType():String{
			return importType;
		}
		public function setXML(xmlPath:String):void{
		}
		
		/**
		 * Returns list of IPatternHeading instances. 
		 * @return 
		 */		
		public function getMenuList():Array {
			return this.menuList;
		}
		
		public function setGLO_manifest(manifest:XML):void{
			GLO_manifest = manifest;
		}
		public function getGLO_manifest():XML{
			return GLO_manifest;
		}
		protected function update(message:String = "modelEvent"):void {
			var modelEvent:ModelEvent = new ModelEvent(message);
			dispatchEvent(modelEvent);
		}

	}//end BaseModel

}