///////////////////////////////////////////////////////////
//  ComponentView.as
//  Macromedia ActionScript Implementation of the Class ComponentView
//  Generated by Enterprise Architect
//  Created on:      06-Nov-2007 13:48:23
//  Original author: USER
///////////////////////////////////////////////////////////

/////////////////////////////////////////////////////////////////////////
// Copyright (c) 2007-09 LTRI, London Metropolitan Uni. All rights reserved.
// An Open Source Release under the GPL v3 licence  (see http://www.gnu.org/licenses/).
// Authors: Tom Boyle, Nils Millahn, Musbah Sagar, Martin Agombar.
// See http://www.glomaker.org for full details
/////////////////////////////////////////////////////////////////////////

package org.glomaker.patternmaker.view
{
	import org.glomaker.patternmaker.events.*;
	
	import flash.display.Sprite;
	import flash.events.*;
	
	import org.glomaker.patternmaker.events.ModelEvent;

	/**
	 * ABSTRACT Class (should be subclassed and not instantiated)
	 * @author USER
	 * @version 1.0
	 * @created 06-Nov-2007 13:48:23
	 */
	public class ComponentView extends Sprite
	{
	    protected var model: Object;
	    protected var controller: Object;

	    /**
	     * CONSTRUCTOR
	     * 
	     * @param aModel
	     * @param aController    aController
	     */
	    public function ComponentView(aModel:Object, aController:Object = null)
	    {
			model = aModel;
			controller = aController;
	    }

	    /**
	     * 
	     * @param c    c
	     */
	    public function add(c:ComponentView): void
	    {
	    }

	    /**
	     * 
	     * @param c    c
	     */
	    public function remove(c:ComponentView): void
	    {
	    }

	    /**
	     * 
	     * @param n    n
	     */
	    public function getChild(n:int): ComponentView
	    { 
			return null;
	    }

	    /**
	     * 
	     * @param e    e
	     */
	    public function update(e:ModelEvent = null): void
	    {
	    }

	}//end ComponentView

}