///////////////////////////////////////////////////////////
//  ComponentViewConcrete1.as
//  Macromedia ActionScript Implementation of the Class ComponentViewConcrete1
//  Generated by Enterprise Architect
//  Created on:      06-Nov-2007 13:48:23
//  Original author: USER
///////////////////////////////////////////////////////////

/////////////////////////////////////////////////////////////////////////
// Copyright (c) 2007-09 LTRI, London Metropolitan Uni. All rights reserved.
// An Open Source Release under the GPL v3 licence  (see http://www.gnu.org/licenses/).
// Authors: Tom Boyle, Nils Millahn, Musbah Sagar, Martin Agombar.
// See http://www.glomaker.org for full details
/////////////////////////////////////////////////////////////////////////

package org.glomaker.patternmaker.view
{
	import flash.events.*;
	import org.glomaker.patternmaker.view.ComponentView;

	/**
	 * @author USER
	 * @version 1.0
	 * @created 06-Nov-2007 13:48:23
	 */
	public class ComponentViewConcrete1 extends ComponentView
	{
	    /**
	     * 
	     * @param aModel
	     * @param aController    aController
	     */
	    public function ComponentViewConcrete1(aModel:IBaseModel, aController:Object = null)
	    {
	    }

	    /**
	     * Get data from model and update view
	     * 
	     * @param e    e
	     */
	    public function update(e:Event = null): void
	    {
	    }

	}//end ComponentViewConcrete1

}