///////////////////////////////////////////////////////////
//  CompositeViewConcrete.as
//  Macromedia ActionScript Implementation of the Class CompositeViewConcrete
//  Generated by Enterprise Architect
//  Created on:      06-Nov-2007 13:48:24
//  Original author: USER
///////////////////////////////////////////////////////////

/////////////////////////////////////////////////////////////////////////
// Copyright (c) 2007-09 LTRI, London Metropolitan Uni. All rights reserved.
// An Open Source Release under the GPL v3 licence  (see http://www.gnu.org/licenses/).
// Authors: Tom Boyle, Nils Millahn, Musbah Sagar, Martin Agombar.
// See http://www.glomaker.org for full details
/////////////////////////////////////////////////////////////////////////

package org.glomaker.patternmaker.view
{
	import flash.events.*;
	import org.glomaker.patternmaker.controller.*;
	import org.glomaker.patternmaker.view.CompositeView;

	/**
	 * @author USER
	 * @version 1.0
	 * @created 06-Nov-2007 13:48:24
	 */
	public class CompositeViewConcrete extends CompositeView {
		/**
		     * CONSTRUCTOR
		     * Requires an addEventListener to trigger onSomeEvent
		     * 
		     * @param aModel    aModel
		     * @param aController    aController
		     */
		public function CompositeViewConcrete(aModel:IBaseModel,aController:IController) {
		}

		/**
		     * 
		     * @param e    e
		     */
		private function onSomeEvent(e:Event):void {
		}

	}//end CompositeViewConcrete

}